import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { AppConfigProvider } from "@/context";
import { ViewTransitions } from "next-view-transitions";
import { LayoutContainer } from "@/components/layout-container";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"], // include weights you need
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="en">
        <body className={`${roboto.variable} antialiased`}>
          <AppConfigProvider>
            <LayoutContainer>{children}</LayoutContainer>
          </AppConfigProvider>
        </body>
      </html>
    </ViewTransitions>
  );
}
